package co.com.kalettre.modelo;
// Generated 19/09/2019 01:37:33 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Especialidad generated by hbm2java
 */
@Entity
@Table(name = "especialidad", schema = "public")
public class Especialidad implements java.io.Serializable {

	private int idEspecialidad;
	private String nombre;
	private Set<Consulta> consultas = new HashSet<Consulta>(0);

	public Especialidad() {
	}

	public Especialidad(int idEspecialidad, String nombre) {
		this.idEspecialidad = idEspecialidad;
		this.nombre = nombre;
	}

	public Especialidad(int idEspecialidad, String nombre, Set<Consulta> consultas) {
		this.idEspecialidad = idEspecialidad;
		this.nombre = nombre;
		this.consultas = consultas;
	}

	@Id

	@Column(name = "id_especialidad", unique = true, nullable = false)
	public int getIdEspecialidad() {
		return this.idEspecialidad;
	}

	public void setIdEspecialidad(int idEspecialidad) {
		this.idEspecialidad = idEspecialidad;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "especialidad")
	public Set<Consulta> getConsultas() {
		return this.consultas;
	}

	public void setConsultas(Set<Consulta> consultas) {
		this.consultas = consultas;
	}

}
