package co.com.kalettre.modelo;
// Generated 19/09/2019 01:37:33 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Examen generated by hbm2java
 */
@Entity
@Table(name = "examen", schema = "public")
public class Examen implements java.io.Serializable {

	private int idExamen;
	private String descripcion;
	private String nombre;
	private Set<Consulta> consultas = new HashSet<Consulta>(0);

	public Examen() {
	}

	public Examen(int idExamen, String descripcion, String nombre) {
		this.idExamen = idExamen;
		this.descripcion = descripcion;
		this.nombre = nombre;
	}

	public Examen(int idExamen, String descripcion, String nombre, Set<Consulta> consultas) {
		this.idExamen = idExamen;
		this.descripcion = descripcion;
		this.nombre = nombre;
		this.consultas = consultas;
	}

	@Id

	@Column(name = "id_examen", unique = true, nullable = false)
	public int getIdExamen() {
		return this.idExamen;
	}

	public void setIdExamen(int idExamen) {
		this.idExamen = idExamen;
	}

	@Column(name = "descripcion", nullable = false, length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "examens")
	public Set<Consulta> getConsultas() {
		return this.consultas;
	}

	public void setConsultas(Set<Consulta> consultas) {
		this.consultas = consultas;
	}

}
