package co.com.kalettre.modelo;
// Generated 19/09/2019 01:37:33 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Medico generated by hbm2java
 */
@Entity
@Table(name = "medico", schema = "public")
public class Medico implements java.io.Serializable {

	private int idMedico;
	private String cmp;
	private String apellidos;
	private String nombres;
	private Set<Consulta> consultas = new HashSet<Consulta>(0);

	public Medico() {
	}

	public Medico(int idMedico, String cmp, String apellidos, String nombres) {
		this.idMedico = idMedico;
		this.cmp = cmp;
		this.apellidos = apellidos;
		this.nombres = nombres;
	}

	public Medico(int idMedico, String cmp, String apellidos, String nombres, Set<Consulta> consultas) {
		this.idMedico = idMedico;
		this.cmp = cmp;
		this.apellidos = apellidos;
		this.nombres = nombres;
		this.consultas = consultas;
	}

	@Id

	@Column(name = "id_medico", unique = true, nullable = false)
	public int getIdMedico() {
		return this.idMedico;
	}

	public void setIdMedico(int idMedico) {
		this.idMedico = idMedico;
	}

	@Column(name = "cmp", nullable = false, length = 12)
	public String getCmp() {
		return this.cmp;
	}

	public void setCmp(String cmp) {
		this.cmp = cmp;
	}

	@Column(name = "apellidos", nullable = false, length = 70)
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@Column(name = "nombres", nullable = false, length = 70)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medico")
	public Set<Consulta> getConsultas() {
		return this.consultas;
	}

	public void setConsultas(Set<Consulta> consultas) {
		this.consultas = consultas;
	}

}
