package co.com.kalettre.modelo;
// Generated 19/09/2019 01:37:33 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "menu", schema = "public")
public class Menu implements java.io.Serializable {

	private int idMenu;
	private String icono;
	private String nombre;
	private String url;
	private Set<MenuRol> menuRols = new HashSet<MenuRol>(0);

	public Menu() {
	}

	public Menu(int idMenu) {
		this.idMenu = idMenu;
	}

	public Menu(int idMenu, String icono, String nombre, String url, Set<MenuRol> menuRols) {
		this.idMenu = idMenu;
		this.icono = icono;
		this.nombre = nombre;
		this.url = url;
		this.menuRols = menuRols;
	}

	@Id

	@Column(name = "id_menu", unique = true, nullable = false)
	public int getIdMenu() {
		return this.idMenu;
	}

	public void setIdMenu(int idMenu) {
		this.idMenu = idMenu;
	}

	@Column(name = "icono", length = 20)
	public String getIcono() {
		return this.icono;
	}

	public void setIcono(String icono) {
		this.icono = icono;
	}

	@Column(name = "nombre", length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "url", length = 50)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menu")
	public Set<MenuRol> getMenuRols() {
		return this.menuRols;
	}

	public void setMenuRols(Set<MenuRol> menuRols) {
		this.menuRols = menuRols;
	}

}
