package co.com.kalettre.modelo;
// Generated 19/09/2019 01:37:33 PM by Hibernate Tools 5.2.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MenuRol generated by hbm2java
 */
@Entity
@Table(name = "menu_rol", schema = "public")
public class MenuRol implements java.io.Serializable {

	private MenuRolId id;
	private Menu menu;
	private Rol rol;

	public MenuRol() {
	}

	public MenuRol(MenuRolId id, Menu menu, Rol rol) {
		this.id = id;
		this.menu = menu;
		this.rol = rol;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idMenu", column = @Column(name = "id_menu", nullable = false)),
			@AttributeOverride(name = "idRol", column = @Column(name = "id_rol", nullable = false)) })
	public MenuRolId getId() {
		return this.id;
	}

	public void setId(MenuRolId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_menu", nullable = false, insertable = false, updatable = false)
	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_rol", nullable = false, insertable = false, updatable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

}
