package co.com.kalettre.modelo;
// Generated 19/09/2019 01:37:33 PM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MenuRolId generated by hbm2java
 */
@Embeddable
public class MenuRolId implements java.io.Serializable {

	private int idMenu;
	private int idRol;

	public MenuRolId() {
	}

	public MenuRolId(int idMenu, int idRol) {
		this.idMenu = idMenu;
		this.idRol = idRol;
	}

	@Column(name = "id_menu", nullable = false)
	public int getIdMenu() {
		return this.idMenu;
	}

	public void setIdMenu(int idMenu) {
		this.idMenu = idMenu;
	}

	@Column(name = "id_rol", nullable = false)
	public int getIdRol() {
		return this.idRol;
	}

	public void setIdRol(int idRol) {
		this.idRol = idRol;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MenuRolId))
			return false;
		MenuRolId castOther = (MenuRolId) other;

		return (this.getIdMenu() == castOther.getIdMenu()) && (this.getIdRol() == castOther.getIdRol());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdMenu();
		result = 37 * result + this.getIdRol();
		return result;
	}

}
