package co.com.kalettre.modelo;
// Generated 19/09/2019 01:37:33 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
 * Paciente generated by hbm2java
 */
@Entity
@Table(name = "paciente", schema = "public")
public class Paciente implements java.io.Serializable {


	private int idPaciente;
	
	private String apellidos;
	private String direccion;
	private String dni;
	private String nombres;
	private String telefono;
	private Set<Signos> signoses = new HashSet<Signos>(0);
	private Set<Consulta> consultas = new HashSet<Consulta>(0);

	public Paciente() {
	}

	public Paciente(int idPaciente, String apellidos, String dni, String nombres) {
		this.idPaciente = idPaciente;
		this.apellidos = apellidos;
		this.dni = dni;
		this.nombres = nombres;
	}

	public Paciente(int idPaciente, String apellidos, String direccion, String dni, String nombres, String telefono,
			Set<Signos> signoses, Set<Consulta> consultas) {
		this.idPaciente = idPaciente;
		this.apellidos = apellidos;
		this.direccion = direccion;
		this.dni = dni;
		this.nombres = nombres;
		this.telefono = telefono;
		this.signoses = signoses;
		this.consultas = consultas;
	}

	@Id

	@Column(name = "id_paciente", unique = true, nullable = false)
	public int getIdPaciente() {
		return this.idPaciente;
	}

	public void setIdPaciente(int idPaciente) {
		this.idPaciente = idPaciente;
	}

	@Column(name = "apellidos", nullable = false, length = 70)
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@Column(name = "direccion", length = 150)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "dni", nullable = false, length = 8)
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	@Column(name = "nombres", nullable = false, length = 70)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "telefono", length = 9)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paciente")
	@LazyCollection(LazyCollectionOption.FALSE)
	public Set<Signos> getSignoses() {
		return this.signoses;
	}

	public void setSignoses(Set<Signos> signoses) {
		this.signoses = signoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paciente")
	@LazyCollection(LazyCollectionOption.FALSE)
	public Set<Consulta> getConsultas() {
		return this.consultas;
	}

	public void setConsultas(Set<Consulta> consultas) {
		this.consultas = consultas;
	}

}
