package co.com.kalettre.modelo;
// Generated 19/09/2019 01:37:33 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ResetToken generated by hbm2java
 */
@Entity
@Table(name = "reset_token", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "token"))
public class ResetToken implements java.io.Serializable {

	private long id;
	private Usuario usuario;
	private Date expiracion;
	private String token;

	public ResetToken() {
	}

	public ResetToken(long id, Usuario usuario, Date expiracion, String token) {
		this.id = id;
		this.usuario = usuario;
		this.expiracion = expiracion;
		this.token = token;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expiracion", nullable = false, length = 29)
	public Date getExpiracion() {
		return this.expiracion;
	}

	public void setExpiracion(Date expiracion) {
		this.expiracion = expiracion;
	}

	@Column(name = "token", unique = true, nullable = false)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

}
