package co.com.kalettre.modelo;
// Generated 19/09/2019 01:37:33 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
public class Usuario implements java.io.Serializable {

	private int idUsuario;
	private boolean estado;
	private String clave;
	private String nombre;
	private Set<UsuarioRol> usuarioRols = new HashSet<UsuarioRol>(0);
	private Set<ResetToken> resetTokens = new HashSet<ResetToken>(0);

	public Usuario() {
	}

	public Usuario(int idUsuario, boolean estado, String clave, String nombre) {
		this.idUsuario = idUsuario;
		this.estado = estado;
		this.clave = clave;
		this.nombre = nombre;
	}

	public Usuario(int idUsuario, boolean estado, String clave, String nombre, Set<UsuarioRol> usuarioRols,
			Set<ResetToken> resetTokens) {
		this.idUsuario = idUsuario;
		this.estado = estado;
		this.clave = clave;
		this.nombre = nombre;
		this.usuarioRols = usuarioRols;
		this.resetTokens = resetTokens;
	}

	@Id

	@Column(name = "id_usuario", unique = true, nullable = false)
	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "estado", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@Column(name = "clave", nullable = false)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "nombre", unique = true, nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<UsuarioRol> getUsuarioRols() {
		return this.usuarioRols;
	}

	public void setUsuarioRols(Set<UsuarioRol> usuarioRols) {
		this.usuarioRols = usuarioRols;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<ResetToken> getResetTokens() {
		return this.resetTokens;
	}

	public void setResetTokens(Set<ResetToken> resetTokens) {
		this.resetTokens = resetTokens;
	}

}
